apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "training-operator.fullname" . }}
  labels:
    {{- include "training-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - list
  - update
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - jaxjobs
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - jaxjobs/finalizers
  verbs:
  - update
- apiGroups:
  - kubeflow.org
  resources:
  - jaxjobs/status
  verbs:
  - update
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs/finalizers
  verbs:
  - update
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs/status
  verbs:
  - update
- apiGroups:
  - kubeflow.org
  resources:
  - paddlejobs
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - paddlejobs/finalizers
  verbs:
  - update
- apiGroups:
  - kubeflow.org
  resources:
  - paddlejobs/status
  verbs:
  - update
- apiGroups:
  - kubeflow.org
  resources:
  - pytorchjobs
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - pytorchjobs/finalizers
  verbs:
  - update
- apiGroups:
  - kubeflow.org
  resources:
  - pytorchjobs/status
  verbs:
  - update
- apiGroups:
  - kubeflow.org
  resources:
  - tfjobs
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - tfjobs/finalizers
  verbs:
  - update
- apiGroups:
  - kubeflow.org
  resources:
  - tfjobs/status
  verbs:
  - update
- apiGroups:
  - kubeflow.org
  resources:
  - xgboostjobs
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - xgboostjobs/finalizers
  verbs:
  - update
- apiGroups:
  - kubeflow.org
  resources:
  - xgboostjobs/status
  verbs:
  - update
{{- if not .Values.mpiDisableRBACManagement }}
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - list
  - watch
{{- end }}
- apiGroups:
  - scheduling.volcano.sh
  resources:
  - podgroups
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - scheduling.x-k8s.io
  resources:
  - podgroups
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
