apiVersion: v1
kind: Secret
metadata:
  name: {{ include "training-operator.webhookCertSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "training-operator.labels" . | nindent 4 }}
type: Opaque
data:
