apiVersion: v1
kind: Service
metadata:
  name: {{ include "training-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "training-operator.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: monitoring-port
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
    - name: webhook-server
      port: {{ .Values.service.webhookPort }}
      targetPort: webhook-server
      protocol: TCP
      appProtocol: https
  selector:
    {{- include "training-operator.selectorLabels" . | nindent 4 }}
