apiVersion: v2
name: training-operator
description: A Helm chart for deploying Kubeflow Training Operator on Kubernetes.
type: application
version: 1.9.3
appVersion: v1.9.3
kubeVersion: ">= 1.19.0-0"
keywords:
  - kubeflow
  - training
  - machine-learning
icon: file://logo.svg
home: https://github.com/AliyunContainerService/trainer/tree/develop
maintainers:
  - name: vicoooo26
    url: https://github.com/vicoooo26
